### ISSUE TITLE
geolocation-db.com DOWN

### ISSUE THREAD

**Issue by VerstreuteSeele** [moom825/Discord-RAT#12]
got any alternative as it breaks 90% of the on_ready script?

**Comment by moom825** [comment]
thats strange. its not down for me? it might be blocked in your location.
feel free to dm in discord if you want further help with this issue.
https://discord.gg/V589WeDmUr

**Comment by moom825** [comment]
lol

**Comment by ltspicer** [comment]
I think, geolocation is definitifely down...
