### ISSUE TITLE
How can I navigate to a directory named "."? & other issues

### ISSUE THREAD

**Issue by kafoby** [moom825/Discord-RAT#18]
A directory on the target computer is named "."
A single period. It seems I'm not able to navigate to it. How can I make the program literally interpret a period in the directory name?
Edit with some other issues:
!screenshot only works for one monitor if multiple are connected
!currentdir doesn't seem to work at all, but this doesn't matter much since !displaydir includes the directory name anyway.

**Comment by moom825** [comment]
The "." just means the current directory, for example let's say you're in
the C drive(C:\\), the "." would = "C:\\". I don't think it is possible to
even create a folder named "." in windows.

Sorry for the late reply.

**Comment by kafoby** [comment]
>

**Comment by kafoby** [comment]
Then there must be a different issue, because in many locations, I see 2 folders named "." and ".."
They even appear in the directory count at the bottom of the report.

**Comment by moom825** [comment]
"." means current directory.
".."  means the directory before.
example:
lets say you are in "C:\\windows"
"." would equal "C:\\windows".
".." would equal "C:\\".
