### ISSUE TITLE
!Passwords

### ISSUE THREAD

**Issue by H3153NB3RGKURD** [moom825/Discord-RAT#19]
Hello Sir thanks for sharing this beautiful project. 
I'm testing your project but i think password grabber isn't working.
can you help me with that please?

**Comment by studentnoo** [comment]
> Hello Sir thanks for sharing this beautiful project. I'm testing your project but i think password grabber isn't working. can you help me with that please?

Hey are u able to run the code because my code is not working its showing Event loop is closed

**Comment by addi00000** [comment]
> > Hello Sir thanks for sharing this beautiful project. I'm testing your project but i think password grabber isn't working. can you help me with that please?
> 
> Hey are u able to run the code because my code is not working its showing Event loop is closed

#6

**Comment by moom825** [comment]
fixed passwords issue
