### ISSUE TITLE
Setup Help

### ISSUE THREAD

**Issue by spongeboymebod** [moom825/Discord-RAT#2]
I'm sure this is a trivial sort of thing, but I'm new to this, so I'm not sure what it precisely means when it says to paste the token at line 20. I've got the token, but I'm unsure of what to use, to put it where it needs to go. Do i need to copy and edit the code in visual studio, or use something else?

**Comment by moom825** [comment]
well you would open it up is any text editor(even notepad) then go to line 20 and you should see this "token = ' ' ". you put your bot token in the single quotes. like this: token = 'putyourtokenhere'. tell me if you understand now.

**Comment by spongeboymebod** [comment]
Alright, cheers, and I do have a text editor. One last thing though, does
it have to be copy and pasted directly from the GitHub page, or downloaded
as a zip and then edited in the respective editor

**Comment by moom825** [comment]
it can be any text editor. and you can download it and unzip or just copy and paste. both will be the same thing.

**Comment by spongeboymebod** [comment]
I encountered another error during setup. I copy and pasted the contents of
requirements.txt into my own txt file, and renamed my own copy to
requirements.txt. but upon entering pip3 install -r requirements.txt into
CMD (with admin on) it gave back ERROR: Could not open requirements file:
[Errno 2] No such file or directory: 'requirements.txt' even though I had
in fact made the file. I didn't see any way to directly download the.txt
file you had provided on the page, so I improvised. I suspect I blundered a
step, or missed something important, and i hope these questions
aren't bothering you. So, what do you think went wrong?

**Comment by moom825** [comment]
i think your problem is that your not in the same directory.
here is what you can do, next to your "requirements.txt" create a .bat file called anything you want. paste the command you were trying to run in there. save it, then double click it. a command prompt should come up and them it should download and everything will work fine.

**Comment by spongeboymebod** [comment]
i did what you said, and it did the trick. though interestingly enough, entering "python DiscordRAT" gives the usual "no such file or directory" error, but entering "python DiscordRAT.py" made it work just fine. the modules i tested seemed to work okay, but one issue that i was able to repeat, involved the !uacbypass command. upon entering it, it opens a new session with admin, but no command entered in this new admin session works. as for the other open issue, it isnt just on their end. running the !getdiscordinfo command does list the tokens location as "Discord"

**Comment by moom825** [comment]
i recently edited the token grabber portion to might have removed something by mistake, ill look in to it. as for your problem with the uac bypass can you message me on discord so i can help you easier?

**Comment by spongeboymebod** [comment]
Sure thing. The name is Sanos#9939
