### ISSUE TITLE
!passwords (please help)

### ISSUE THREAD

**Issue by rishieyt123456** [moom825/Discord-RAT#24]
please help me the discord rat is working very nicely but, the !passwords command is not working leading to no significant (what i think) meaning of this tool 

please if you could, help me out just reply 

thanks :)

**Comment by moom825** [comment]
this is a project i stopped working on a while ago. in the future i might
remake it, but im currently working on a new project that i currently find
more interesting.

**Comment by moom825** [comment]
fixed
