### ISSUE TITLE
Bit complicated: invisible background process

### ISSUE THREAD

**Issue by UnknownLemonade** [moom825/Discord-RAT#26]
How can I set the window to be made invisible? (e.B. as a background process) In addition, I want to ask how I can activate that the window opens automatically after a restart? (again as an invisible background process)

**Comment by moom825** [comment]
#20 

this what your looking for?

**Comment by UnknownLemonade** [comment]
Yup, but I didn't quite know where to write this suggestion/question...

**Comment by moom825** [comment]
so is the comment closed or do you another issue/suggestions

**Comment by UnknownLemonade** [comment]
Nope, no more issues or suggestions.

**Comment by moom825** [comment]
k
