### ISSUE TITLE
Erros

### ISSUE THREAD

**Issue by GipiXETH** [moom825/Discord-RAT#27]
error :  File "C:\Users\gipix\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
FIX?

**Comment by GipiXETH** [comment]
This too :   File "C:\Users\gipix\Desktop\DiscordRAT.py", line 141, in on_ready
    biggest = max(map(int, result))
ValueError: max() arg is an empty sequence

**Comment by moom825** [comment]
use python 3.9
