### ISSUE TITLE
Any Way to stop it creating sessions on every startup of the same pc?

### ISSUE THREAD

**Issue by ArisCuber19** [moom825/Discord-RAT#29]
I know it can seem a stupid question and probably it's also really hard to do, but is there a way to make the bot generate only a channel / pc? Amazing work btw

**Comment by coazyy** [comment]
how did u run it
not doing anything for me?

**Comment by texas-john** [comment]
> I know it can seem a stupid question and probably it's also really hard to do, but is there a way to make the bot generate only a channel / pc? Amazing work btw

Yes, you can make the channel name a mac address and only create a new channel if the mac address is not a channel name

**Comment by moom825** [comment]
this is a project i havent worked on in a while, and i dont plan to be adding that srry

**Comment by MRXCLAYZERO** [comment]
> > I know it can seem a stupid question and probably it's also really hard to do, but is there a way to make the bot generate only a channel / pc? Amazing work btw
> 
> Yes, you can make the channel name a mac address and only create a new channel if the mac address is not a channel name

how?
