### ISSUE TITLE
What happened to !getdiscordinfo?

### ISSUE THREAD

**Issue by YumYummity** [moom825/Discord-RAT#30]
In commit https://github.com/moom825/Discord-RAT/commit/b842a0a7790f217511b36d6f0ced4acf2a96953a, you removed the **!getdiscordinfo** command, without explanation other than "fixed passwords and other problems". Is there any reason for this, and is it possible for you to add it again? Thanks.

**Comment by moom825** [comment]
discord has added "token encryption" and all tokens are encrypted, i
already have a decrypter for it i just havent gotten the time to update it

**Comment by YumYummity** [comment]
Ok, do you know when it might be re-added?

**Comment by moom825** [comment]
no clue and i rlly dont wanna test it cause everytime i setup a discordrat
bot my account gets termed a week later

**Comment by YumYummity** [comment]
You could create a branch, and I can test it with my own account.

**Comment by moom825** [comment]
if you want feel free to message me on discord (moom825#9999)
