### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by 3dpro45** [moom825/Discord-RAT#31]
how do i set this thing up?? 
the readme.md is very much out of date, and i cant figure out how to make this work! i did everything it says to do, and it did nothing on running. and when i ran "python DiscordRAT" it just said no file existed! somthig is messsed up. plus, how am i supposed to infect another pc?

pls answer soon, thanks!

**Comment by 3dpro45** [comment]
also, a video tutorial would be helpful.

**Comment by moom825** [comment]
a video tutorial will never happen(at least by me) and the command you just
said you ran is not even in the readme(which is not outdated), if you have
other issues feel free to join the discord server

**Comment by moom825** [comment]
mb about the readme part, made a type

**Comment by 3dpro45** [comment]
Np about the typo.


So, could you pls make a more step by step Readme? If so thanks! Also, you never answered my original question:

How do you transfer this to the victom? And also the bot never made a channel or did anything that the Readme said it would. Thank you for your time.

**Comment by moom825** [comment]
well if you ran it properly and the channel was not created, the problem is
most likely with the bot, you prob forgot to give the bot administrator
perms on the server

**Comment by 3dpro45** [comment]
No sorry, I made sure to give the bot every admin perm and even made a role
for the bot that gave it full admin.

It still did nothing.

**Comment by moom825** [comment]
try making sure the bot is only in one server

**Comment by 3dpro45** [comment]
It's only in one server
