### ISSUE TITLE
win32gui error

### ISSUE THREAD

**Issue by MRXCLAYZERO** [moom825/Discord-RAT#38]
When I typed pip3 install -r requirements.txt I got an error: ,,[end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.", Then I tried to install the requirements manually again, everything worked except for win32gui. I searched the internet for errors the whole time, but unfortunately nothing found a suitable one.

**Comment by moom825** [comment]
try `pip install pywin32`
