### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by IamVlad01** [moom825/Discord-RAT#41]
Hi, I am trying to compile and I am getting an error
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\utils\hooks\__init__.py", line 582, in get_package_paths
    raise ValueError(f"Package '{package}' does not exist or is not a package!")
ValueError: Package 'sounddevice' does not exist or is not a package!

Can someone help me?

**Comment by Navoichyk** [comment]
> Hi, I am trying to compile and I am getting an error File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\utils\hooks__init__.py", line 582, in get_package_paths raise ValueError(f"Package '{package}' does not exist or is not a package!") ValueError: Package 'sounddevice' does not exist or is not a package!
> 
> Can someone help me?

It says right there what you’re missing. Download the sounddevice package…
